[package]
name = "bedrock"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]

[dependencies]
axum = "0.4.4"
hyper = { version = "0.14", features = ["full"] }
serde = {version = "1", features = ["derive"]}
serde_json = "1"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version="0.3", features = ["env-filter"] }
tower-http = { version = "0.2.0", features = ["trace"] }

[dev-dependencies]
tower = { version = "0.4", features = ["util"] }
